# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whoes values do not exceed
# four million, find the sum of the even-valued terms.

solution = ->
  sum = 0
  n1 = 1
  n2 = 2

  # Need to loop up to 4 million
  while n2 <= 4000000
    # By using mod 2, we can check if the number is even
    sum += n2 if n2 % 2 is 0
    # The next iteration n2 will be the current n1 + n2
    n2 += n1
    # The next iteration n1 will be the current n2 (but before n1 was added!)
    # Note: temporary variable could be used instead
    n1 = n2 - n1

  return sum

console.log solution()
